version: '1.1'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MSQL_USER: docker
      MYSQL_ROOT_PASSWORD: password
      MSQL_PASSWORD: password
      MYSQL_DATABASE: godocker
    ports:
      - "3306:3306"
